digitalmarketplace/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls', namespace='products')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products.views import ProductDetailView, ProductListView, ProductCreateView, ProductUpdateView, ProductDeleteView, \
    ProductDownloadView

app_name = "products"
urlpatterns = [
    path('', ProductListView.as_view(), name="index"),
    path('<int:pk>', ProductDetailView.as_view(), name="detail"),
    path('<slug:slug>', ProductDetailView.as_view(), name="detail_slug"),
    path('<int:id>/download', ProductDownloadView.as_view(), name="download"),
    path('<slug:slug>/download', ProductDownloadView.as_view(), name="download_slug"),
    path('create/', ProductCreateView.as_view(), name="create"),
    path('<int:pk>/edit', ProductUpdateView.as_view(), name="update"),
    path('<slug:slug>/edit', ProductUpdateView.as_view(), name="update_slug"),
    path('<int:pk>/delete', ProductDeleteView.as_view(), name="delete"),
    path('<slug:slug>/delete', ProductDeleteView.as_view(), name="delete_slug"),
]

products/models.py
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.db import models

# Create your models here.
from django.db.models.signals import pre_save
from django.utils.text import slugify

def user_directory_path(instance, filename):
    # file will be uploaded to MEDIA_ROOT/user_<id>/<filename>
    return 'user_{0}/{1}'.format(instance.user.id, filename)

class Product(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    media = models.FileField(upload_to=user_directory_path, blank=True, null=True,
                             storage=FileSystemStorage(location=settings.PROTECTED_ROOT))
    title = models.CharField(max_length=120)
    description = models.TextField()
    price = models.DecimalField(max_digits=100, decimal_places=2)
    sale_price = models.DecimalField(max_digits=100, decimal_places=2, null=True, default=0.0, blank=True)
    slug = models.SlugField(null=True, unique=True)

    def __str__(self):
        return self.title


def create_slug(instance, new_slug=None):
    slug = slugify(instance.title)
    if new_slug is not None:
        slug = new_slug
    qs = Product.objects.filter(slug=slug)
    exists = qs.exists()
    if exists:
        new_slug = "%s-%s" %(slug, qs.first().id)
        return create_slug(instance, new_slug=new_slug)
    return slug

def product_pre_save_db(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = create_slug(instance)

pre_save.connect(product_pre_save_db, sender=Product)

products/forms.py
from django import forms
from django.forms import Textarea, TextInput
from django.utils.text import slugify

from products.models import Product


class ProductAddForm(forms.ModelForm):
    class Meta:
        model = Product

        fields = [
            "title",
            "description",
            "price"
        ]
        widgets = {
            "description": Textarea(
                attrs={
                    "placeholder": "New Description",
                }
            ),
            "title": TextInput(
                attrs={
                    "placeholder": "Title",
                }
            ),
        }

    def clean(self):
        cleaned_data = super(ProductAddForm, self).clean()
        # title = cleaned_data.get("title")
        # slug = slugify(title)
        # qs = Product.objects.filter(slug=slug).exists()
        # if qs:
        #     raise forms.ValidationError("Title is taken, new title is needed.  Please try again.")
        return cleaned_data

products/views.py
# Create your views here.
import os
from mimetypes import guess_type
from wsgiref.util import FileWrapper

from django.conf import settings
from django.http import HttpResponse, FileResponse
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, CreateView, UpdateView, DeleteView
from django.db.models import Q

from digitalmarketplace.mixins import MultiSlugMixin
from products.forms import ProductAddForm
from .models import Product


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductAddForm
    success_url = reverse_lazy('products:index')

    def form_valid(self, form):
        # form.Meta.model.user_id = self.request.user.id
        f = form.save(commit=False)
        f.submitter_field = self.request.user
        f.save()
        super().form_valid(form)


class ProductDetailView(MultiSlugMixin, DetailView):
    model = Product


class ProductListView(ListView):
    def get_queryset(self):
        query = self.request.GET.get("q")
        if query:
            return Product.objects.filter(Q(title__icontains=query)|Q(description__icontains=query))
        """Return the last five published questions."""
        return Product.objects.order_by('-price')  # [:5]


class ProductUpdateView(UpdateView):
    model = Product
    fields = ["title", "description", "price", "sale_price"]

    success_url = reverse_lazy('products:index')

    def get_context_data(self, *args, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(*args, **kwargs)
        context["submit_btn"] = "Update"
        return context


class ProductDeleteView(DeleteView):
    model = Product

    success_url = reverse_lazy('products:index')


class ProductDownloadView(MultiSlugMixin, DetailView):
    model = Product

    def get(self, request, *args, **kwargs):
        obj = self.get_object()
        filepath = os.path.join(settings.PROTECTED_ROOT, obj.media.path)
        # print(response)
        guessed_type = guess_type(filepath)[0]
        mimetype = 'application/force-download'
        if guessed_type:
            mimetype = guessed_type
        response = FileResponse(open(filepath, 'rb'), content_type=mimetype)
        # """ Header information for the html """
        if not request.GET.get('preview'):
            response["Content-Disposition"] = f"attachment; filename={obj.media.name}"
        response["X-SendFile"] = str(obj.media.name)
        return response

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
{#    <title>Title</title>#}
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/product/detail.html
{% extends "base.html" %}

{% block title %}
    <title>Product Detial</title>
{% endblock %}

{% block content %}

    <h1>{{ product_detail.title }}</h1>
    <p>{{ product_detail.description }}</p>
    <p>Price: {{ product_detail.price }}</p>
    <p>Sale Price: {{ product_detail.sale_price }}</p>
{% endblock %}

templates/product/index.html
{% extends "base.html" %}

{% block title %}
    <title>Product List</title>
{% endblock %}

{% block content %}
    <form action="{% url 'products:create' %}">
        <button>Create Product</button>
    </form>
    <table style="width: 100%">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
        </tr>
        {% for product in product_list %}
            <tr>
                <td><a href="{% url 'products:detail' slug=product.slug %}">{{ product.title }}</a></td>
                <td>{{ product.description }}</td>
                <td>{{ product.price }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}

templates/products/form_include.html
<form method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value={{ submit_btn|default:"Add" }}>
</form>

templates/products/product_confirm_delete.html
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

templates/products/product_detail.html
{% extends "base.html" %}

{% block title %}
    <title>Product Detail</title>
{% endblock %}

{% block content %}

    <h1><a href={% url 'products:download_slug' slug=object.slug %}>{{ object.title }}</a></h1>
    <p><a href={% url 'products:download_slug' slug=object.slug  %}?preview=True>Preview</a></p>
    <p>{{ object.description }}</p>
    <p>Price: {{ object.price }}</p>
    <p>Sale Price: {{ object.sale_price }}</p>
{% endblock %}

templates/products/product_form.html
{% extends "base.html" %}

{% block title %}
    <title>Product Create</title>
{% endblock %}

{% block content %}
    {% include "products/form_include.html" with submit_btn=submit_btn %}
{% endblock %}

templates/products/product_list.html
{% extends "base.html" %}

{% block title %}
    <title>Product List</title>
{% endblock %}

{% block content %}
    <form action="{% url 'products:create' %}">
        <button>Create Product</button>
    </form>
    <form action="" method="get">
        <input type="text" name="q" placeholder="Search" value="{{ request.GET.q }}">
        <input type="submit" value="Search">
    </form>
    <table style="width: 100%">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Price</th>
        </tr>
        {% for product in object_list %}
            <tr>
                <td><a href="{% url 'products:detail_slug' slug=product.slug %}">{{ product.title }}</a></td>
                <td>{{ product.description }}</td>
                <td>{{ product.price }}</td>
            </tr>
        {% endfor %}
    </table>
{% endblock %}